spring.application.name=echodeck_backend_470sp25_team3
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/echodeck
spring.datasource.username=postgres
spring.datasource.password=sesame
spring.datasource.driver-class-name=org.postgresql.Driver

# Used by JPA to create the `users` table
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret Key (Replace with a long, random Base64 string)
jwt.secret=vFRyhLU64tALgB93Sjm8tiSbSqpu4MeRcrmle4o0NDE=